# This file is generated by Nx.
#
# Build the docker image with `npx nx docker-build Node_NX`.
# Tip: Modify "docker-build" options in project.json to change docker build args.
#
# Run the container with `docker run -p 3000:3000 -t Node_NX`.
FROM docker.io/node:lts-alpine

ENV HOST=0.0.0.0
ENV PORT=3000

WORKDIR /app

RUN addgroup --system Node_NX && \
          adduser --system -G Node_NX Node_NX

COPY dist/Node_NX Node_NX/
RUN chown -R Node_NX:Node_NX .

# You can remove this install step if you build with `--bundle` option.
# The bundled output will include external dependencies.
RUN npm --prefix Node_NX --omit=dev -f install

CMD [ "node", "Node_NX" ]
